apiVersion: v1
kind: Secret
metadata:
    name: tawala-secrets
    namespace: nethub
type: Opaque
stringData:
    #ENC[AES256_GCM,data:nE+qXrUOcMzgNNbl2VzHF4XqNQ==,iv:Hyd6Ej3vsPAvnZybCCNKeJhgRA8U2l173JOZIUAtgJE=,tag:f68FJMzZIL5/NmoxjBIzcQ==,type:comment]
    ENVIRONMENT: ENC[AES256_GCM,data:sUTuZAEJWNCy2A==,iv:zCBp1TInyVm7O03AKXq/0bf7s2Ctt6Ul0Qqgf2OyHcs=,tag:lkoV+Yg2MJnP9Su6WRAEbQ==,type:str]
    APP_NAME: ENC[AES256_GCM,data:Z7BVjWq2iONw2C1/BjI99AiGh7hA71GbIwxFeP68cNcv,iv:sZqUSko7EHGOqTmXdWBB/LCeueZ822EYPiYLDqgTx/E=,tag:kYq+uS2zinXEsKHBeMI2Fw==,type:str]
    APP_VERSION: ENC[AES256_GCM,data:CNnIssznhw==,iv:ARfixbmY2auFsMO5GH1uF7rXkGx0wIMbInfaFRSy6KY=,tag:72Q/M2Y67XwXhd4iYUlOWA==,type:str]
    APP_DESCRIPTION: ENC[AES256_GCM,data:CPzb6jxWSEsXY664i6wij+zg6wpZe0CfRTLbJ6+1ohPf/mxGwZcXmlLFAR87CmgqPsVpjcKwSMroX9aGaOhxsJPnRX7MNjFSQVtIJ43OkZJtrYPf7rKp/2VURyKDOSc=,iv:qD3UOv8l4Ymo2uQoqVYdghcJZBxvm6U8p+ekz1Fj4IY=,tag:r1ufwC2Ma7IqBaZmvnPaBg==,type:str]
    #ENC[AES256_GCM,data:wzRJZPKxW5PIiHZtn7nHKSg=,iv:tPrA1ZoIjeXcdZnB/gZAaNCAy1/zCoBFKkyigFYBq4U=,tag:p5X2un8vbfg4qxPWitfI5A==,type:comment]
    DATABASE_USER: ENC[AES256_GCM,data:s0/NjxsfY7PqAA==,iv:ZOdYNt28WBMgy4Dy9VRhVIXFKVlXPl7H2I3JFuZVJ+A=,tag:qTu77kpFwX4YEC/Z0zFSQg==,type:str]
    DATABASE_PASSWORD: ENC[AES256_GCM,data:q5Lr+dQ0OrN7hg==,iv:/kRsKbNeBK21A7JjeCTxaCAgNCjdQ4cwQTlMPAx+v1c=,tag:bUZMQ09NocwYLadQn/HHzg==,type:str]
    DATABASE_NAME: ENC[AES256_GCM,data:X42G6CmeFVCudg==,iv:tv9WZKWwIee13XbmAgqymIq0UMHyK229ET3ANJXyPRU=,tag:zYn7pndtkRan+H45ClDjrg==,type:str]
    DATABASE_HOST: ENC[AES256_GCM,data:9OEHcBWPLzbAUg==,iv:UnRXtBzI/UK62siWL1rDVSg8xYRtyTQNO9u0AOaa6+Q=,tag:jaBixXtfD29malZZy6BqHw==,type:str]
    DATABASE_PORT: ENC[AES256_GCM,data:nz8jzA==,iv:w/BQmfFMJ6jUNI1q3TeWxqTmqClkTCpmRoGAEPKnKpY=,tag:JO15mDNNWX6IGDe8YV86qw==,type:str]
    #ENC[AES256_GCM,data:GQckGaP0z7ynMqVLSxvnOL9AKJxa7PQ=,iv:oEIR6M/Ygrb9XlV/25rqwnlpCf54FDYIs1hWwKxggBg=,tag:JR8SF8JhYQSutDQiAUIdlg==,type:comment]
    SECRET_KEY: ENC[AES256_GCM,data:x1fuelziGTvf+w==,iv:edZrIcXJI5yV0XBYzcJN062CKWzCwuVSk5oXP2FWLp8=,tag:gB0AVdo/7ItZxorrW39fmQ==,type:str]
    ALGORITHM: ENC[AES256_GCM,data:NA0+r18=,iv:2aWhpGLI28hf0tlXvKlFC3/RUw7tyt5ORCuBbrr+qv8=,tag:9eNV7Gx0x5KTmQIjl1EHnQ==,type:str]
    ISSUER: ENC[AES256_GCM,data:dIlGzqQYFhtxbg==,iv:M2tzdJ2CILNeMcaveunwI7zYuqo7SYcl0Q8ujy1f4Ok=,tag:pbINcQMY1FNv4q6Ev/q1YA==,type:str]
    AUDIENCE: ENC[AES256_GCM,data:cvCaWrNxzlVk4Q==,iv:uANVVfyHkPLd/fk6TgvJV7rKjG3drlEZd/m+/1pUsSQ=,tag:S28yxibuxT67uFLfQNC9wg==,type:str]
    ACCESS_TOKEN_EXPIRE_MINUTES: ENC[AES256_GCM,data:6ug=,iv:5Datw/NpDVuOU/aleJtIlizzOkcM5KGsnDM+/Hljs1Q=,tag:NylPAipeG0Ha/fXaU6iNxQ==,type:str]
    REFRESH_TOKEN_EXPIRE_DAYS: ENC[AES256_GCM,data:Hg==,iv:WwpC1EW1YUExSyj91RvTIcp5hE4p3hFSr1AKp3J37pM=,tag:moW28/Y11XRsAduWjepqoA==,type:str]
    PIN_TOKEN_EXPIRE_HOURS: ENC[AES256_GCM,data:sPo=,iv:BznqLB+gsxJdtXo1uhGFoudjNuq+sbfmGkqQIpcj/Kk=,tag:hUCg8S3+86qp5u8vnhlzjA==,type:str]
    ADMIN_ROUTE: ENC[AES256_GCM,data:QKuLR7RoyxWWmQ==,iv:64UpTfIid1Tp1cboJ1942xi9rOnVZenKUHtkk2p+E2U=,tag:+r3ZpHPMQ5T+B4dOzhfJkw==,type:str]
    RESOURCE_SERVER: ENC[AES256_GCM,data:lI51rQV2aFbeKg==,iv:A9vhJFzmtKZXuE2gpl9I2WhKCLK2mb3ZFuqewvpLaAY=,tag:Y0mjMA6aPn2udr/mNESUfg==,type:str]
    ALLOWED_ORIGINS: ENC[AES256_GCM,data:lUds47VnPjfi/1MiExkAvLFAaBWWsWeoRxnajCLsRmVnuBlumKTSUSJr0skl1pNjgx1NyTd12gWRWGNJzh4N,iv:q7ZKSWrm9bY5egqxpT1lTWy4BPrTaqJtN8NmDixSlro=,tag:GFc7MVveJWmyluBzNblHiQ==,type:str]
    #ENC[AES256_GCM,data:c8c4JpnGDUpHtWZym0p8WrxpdPVJ8z6rWEw=,iv:PQ1m8aU4aDbb8p9fMq6207WsqiN4G1cPI+TowcHMzWo=,tag:NxiDM9WGIy6vYAm71bxY7w==,type:comment]
    RESEND_API_KEY: ENC[AES256_GCM,data:SpMwhXyYH3PcPw==,iv:jcnHesjTjY0Ldaxx/tMQrf4/EUEYCFFcs3sPwe7q6Qw=,tag:fSkFuuVcWf3scTU6y3WIpA==,type:str]
    REDIS_URL: ENC[AES256_GCM,data:staw46+3WqyK8A==,iv:fE0vOtSDx2sMmDuvYOD7mXAS02WfUW8/vWmRwfs4YJs=,tag:GrD+1aMynAm96UXZGiFgjw==,type:str]
    #ENC[AES256_GCM,data:uYXGY0EtSVW+j8ct5O3Ss6jwmYnntUwwuY4P/NrAQ41QOyMx7F02oFEQYjZb2Sfi432n,iv:c40WUTktYCDfUiAPVCKKgcIGN+aVQwTT1gG4SGw24Yo=,tag:SvI+Dm2shtp4EST39NIEOw==,type:comment]
    ADMIN_NAME: ENC[AES256_GCM,data:UZUwlXk+UfI/1g==,iv:Rb/j3wr3v6aFgzD3DqOMWhnX3NzVRIppIlatPQJ1HXQ=,tag:dzsIBPhq0wYF+D+C+KBsUg==,type:str]
    ADMIN_EMAIL: ENC[AES256_GCM,data:uAOcOQrmjWi6MQ==,iv:ACCBn/aaCwDX4Xbt7O2ZtObrhxrDivOYTXjks0B1suQ=,tag:KyjRKPLae/bivwPCPonNow==,type:str]
    ADMIN_PASSWORD: ENC[AES256_GCM,data:BHzksqKcDAYvwQ==,iv:uA6QjcGlk3iSAXhRAlNuLIsuUdeMRy161CKL6YiCGHM=,tag:xC9mQTKvKMx6RLKEX3manQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wy58yxmfdehpfyzwkw3kvqfkv0ze65lyf6yuhe5xt5n6md0vhyssnqkf2t
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtOGJ6cFYrMDBzVG5EZlo4
            d3ZIeEQyaE84Z2xFL2c2Ylo0NklQZXI1aFVvCnM2TFV0Q3ZLZjE1d0IwS0phMlF0
            eWFoakZ3WWZzbHYxQTdaTXhFMEUxM1kKLS0tIGRmdU8vN05NZ3B0b2ZnMFRBakxh
            ZFhGUTRCNEtDME9LY0lZbEUzWTNtVTQKFGGnW/tLx0WfIN5+xD34sC5J9lqsceZM
            QwwZdqhLB0jvX90CjBOzldHXqx92I5s+GweZ1ZMyoh2vc5BSdQKeyg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-01T13:43:29Z"
    mac: ENC[AES256_GCM,data:wHqEzRh8O3Qr03VrJq196kDj0YZVv/XNJdYJ4phFyiqMofzyf2wzedgBGhE9of/OsXROq5MW4cEBTFQtGzsUn6YhP8hRqrYzCDqdEGa5bG/sR21jo1PaJCvk4ytzadA3nH9apOnHfw8oMhRppXT32Jyn/WfM98MuHlJQFDeySN8=,iv:tGwBMG9BZL6cLXNZfvXNG0IVZ2PWBWIdXpb5kEA3E0Y=,tag:Trm/B249y9wmGIU1GbJiNQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
