apiVersion: v1
kind: Secret
metadata:
    name: tawala-secrets
    namespace: nethub
type: Opaque
stringData:
    #ENC[AES256_GCM,data:nE+qXrUOcMzgNNbl2VzHF4XqNQ==,iv:Hyd6Ej3vsPAvnZybCCNKeJhgRA8U2l173JOZIUAtgJE=,tag:f68FJMzZIL5/NmoxjBIzcQ==,type:comment]
    ENVIRONMENT: ENC[AES256_GCM,data:sUTuZAEJWNCy2A==,iv:zCBp1TInyVm7O03AKXq/0bf7s2Ctt6Ul0Qqgf2OyHcs=,tag:lkoV+Yg2MJnP9Su6WRAEbQ==,type:str]
    APP_NAME: ENC[AES256_GCM,data:Z7BVjWq2iONw2C1/BjI99AiGh7hA71GbIwxFeP68cNcv,iv:sZqUSko7EHGOqTmXdWBB/LCeueZ822EYPiYLDqgTx/E=,tag:kYq+uS2zinXEsKHBeMI2Fw==,type:str]
    APP_VERSION: ENC[AES256_GCM,data:CNnIssznhw==,iv:ARfixbmY2auFsMO5GH1uF7rXkGx0wIMbInfaFRSy6KY=,tag:72Q/M2Y67XwXhd4iYUlOWA==,type:str]
    APP_DESCRIPTION: ENC[AES256_GCM,data:CPzb6jxWSEsXY664i6wij+zg6wpZe0CfRTLbJ6+1ohPf/mxGwZcXmlLFAR87CmgqPsVpjcKwSMroX9aGaOhxsJPnRX7MNjFSQVtIJ43OkZJtrYPf7rKp/2VURyKDOSc=,iv:qD3UOv8l4Ymo2uQoqVYdghcJZBxvm6U8p+ekz1Fj4IY=,tag:r1ufwC2Ma7IqBaZmvnPaBg==,type:str]
    #ENC[AES256_GCM,data:wzRJZPKxW5PIiHZtn7nHKSg=,iv:tPrA1ZoIjeXcdZnB/gZAaNCAy1/zCoBFKkyigFYBq4U=,tag:p5X2un8vbfg4qxPWitfI5A==,type:comment]
    DATABASE_USER: ENC[AES256_GCM,data:BB80CfTV7p7HdERu,iv:e3QFc/vkf/neSOUaDLNHgpOEavvO3Ftjrrz1MiHKiJk=,tag:IVxjnnFrufSIup4jdV9/jw==,type:str]
    DATABASE_PASSWORD: ENC[AES256_GCM,data:i+DYMw8cfGOt8PIemWnTsxGoSMxP2Q==,iv:XMWKMDmoVbNEbg/uFPqJqaoDl/fl80lXnvjrs2pGx1U=,tag:M628eAuNb+FBma+Fy4YjFQ==,type:str]
    DATABASE_NAME: ENC[AES256_GCM,data:31JP0Xjgqcms,iv:OPGR/pMt9krSGhxLo1Qjqh++d7rxAlM3SpqBg8DAaWE=,tag:xXFW8a+1URkPYfDwUPZtzw==,type:str]
    DATABASE_HOST: ENC[AES256_GCM,data:+K3HDhBKX2QSTtcEtPojhJkayvz7UAXKTH8YSMC1alLvjqRkbfErmt1kyQ==,iv:+VI/gh2rxZgOjPQaYSU2xLoQyJ/9atL3TDJISSOeo4E=,tag:U33dxxbw4xXRhraHNMfsrQ==,type:str]
    DATABASE_PORT: ENC[AES256_GCM,data:nz8jzA==,iv:w/BQmfFMJ6jUNI1q3TeWxqTmqClkTCpmRoGAEPKnKpY=,tag:JO15mDNNWX6IGDe8YV86qw==,type:str]
    #ENC[AES256_GCM,data:GQckGaP0z7ynMqVLSxvnOL9AKJxa7PQ=,iv:oEIR6M/Ygrb9XlV/25rqwnlpCf54FDYIs1hWwKxggBg=,tag:JR8SF8JhYQSutDQiAUIdlg==,type:comment]
    SECRET_KEY: ENC[AES256_GCM,data:tCEnvob+uiS5kBwFodd9BaSvarUfYKVcgaoFtr+DcY9460VFbQ==,iv:x00F4gEUuczYgcAGhtcULj4r52kdddWngVnIUqoXGSs=,tag:4Kzmkng4ctdG92yWXxiu+w==,type:str]
    ALGORITHM: ENC[AES256_GCM,data:NA0+r18=,iv:2aWhpGLI28hf0tlXvKlFC3/RUw7tyt5ORCuBbrr+qv8=,tag:9eNV7Gx0x5KTmQIjl1EHnQ==,type:str]
    ISSUER: ENC[AES256_GCM,data:ziIUNSTCBw80wl9klQrZYeP74Zy3AwfJPUiKo4Ge7/Qr3N4=,iv:5cNv/RkNW0JzwVrO3xcDUJNEgB8AE3L1RfI82Zpk5QA=,tag:PidlPckIMN4ehuI0tjHsdQ==,type:str]
    AUDIENCE: ENC[AES256_GCM,data:4s0RHUhDCgz+zg==,iv:nvb89HGo0uMQMFVsaor8ynFH/dS3jdmRw9IhJJAxirA=,tag:Z+Kg8/RxGND/mPUGxgGt+Q==,type:str]
    ACCESS_TOKEN_EXPIRE_MINUTES: ENC[AES256_GCM,data:6ug=,iv:5Datw/NpDVuOU/aleJtIlizzOkcM5KGsnDM+/Hljs1Q=,tag:NylPAipeG0Ha/fXaU6iNxQ==,type:str]
    REFRESH_TOKEN_EXPIRE_DAYS: ENC[AES256_GCM,data:Hg==,iv:WwpC1EW1YUExSyj91RvTIcp5hE4p3hFSr1AKp3J37pM=,tag:moW28/Y11XRsAduWjepqoA==,type:str]
    PIN_TOKEN_EXPIRE_HOURS: ENC[AES256_GCM,data:sPo=,iv:BznqLB+gsxJdtXo1uhGFoudjNuq+sbfmGkqQIpcj/Kk=,tag:hUCg8S3+86qp5u8vnhlzjA==,type:str]
    ADMIN_ROUTE: ENC[AES256_GCM,data:urjWbtk=,iv:slCPIswFQVE5Tz3EIaE2Nz52+NWhjypktQzJ/s8ZpqA=,tag:Ve9o+ddq5UUZhh78TQCH8Q==,type:str]
    RESOURCE_SERVER: ENC[AES256_GCM,data:gFEDiDdcqLBnEgxVn4B0/AWIEMtIBJehdGtMn7sKsA==,iv:Q6ogr/khyIm/rCIhSVUq1FB7o0e6gs2dLTvA1XreQIw=,tag:J9PCy/xwzCjWbaCnVxin+Q==,type:str]
    ALLOWED_ORIGINS: ENC[AES256_GCM,data:lUds47VnPjfi/1MiExkAvLFAaBWWsWeoRxnajCLsRmVnuBlumKTSUSJr0skl1pNjgx1NyTd12gWRWGNJzh4N,iv:q7ZKSWrm9bY5egqxpT1lTWy4BPrTaqJtN8NmDixSlro=,tag:GFc7MVveJWmyluBzNblHiQ==,type:str]
    #ENC[AES256_GCM,data:c8c4JpnGDUpHtWZym0p8WrxpdPVJ8z6rWEw=,iv:PQ1m8aU4aDbb8p9fMq6207WsqiN4G1cPI+TowcHMzWo=,tag:NxiDM9WGIy6vYAm71bxY7w==,type:comment]
    RESEND_API_KEY: ENC[AES256_GCM,data:SNUwjua8t34EEVrIPiXhGgR16MAg8zvvs2fZtA//VpUNZil0,iv:f34hbugt+eV0JG+MH+DrZBxgQshJMXnJ/fyob1tPZBc=,tag:2HesUn+s1/YgoDar1jydFw==,type:str]
    REDIS_URL: ENC[AES256_GCM,data:pyyqe+F0c3ytPjMghIpNIysIxQZARQNmdYZhK+T5DmoHgJitJL4lX22wW784oMr2D36PyRSyxa/+jhI2PmZ2,iv:/fiBqNCHyWQhGkgPN3/jsLwkkk1Lz5EtAXSKuojDllY=,tag:RYDAqzZPsa1XF0t7N4s8Fw==,type:str]
    #ENC[AES256_GCM,data:uYXGY0EtSVW+j8ct5O3Ss6jwmYnntUwwuY4P/NrAQ41QOyMx7F02oFEQYjZb2Sfi432n,iv:c40WUTktYCDfUiAPVCKKgcIGN+aVQwTT1gG4SGw24Yo=,tag:SvI+Dm2shtp4EST39NIEOw==,type:comment]
    ADMIN_NAME: ENC[AES256_GCM,data:tkerGLf3YU2TvbmtTw==,iv:v6IyhUkS1t7vMhNWrt0WJBzPQxsjo0xixugzIZAENF0=,tag:WCBH4sjkU0KKWQdXIdxM9w==,type:str]
    ADMIN_EMAIL: ENC[AES256_GCM,data:FO8meE9uoKnrvbzOYZYnmE6DpXt0,iv:mZClnDC4bBY+T+ku2XLlOYpY40ZOinkphD1J8VjDSl4=,tag:y9rLM6SKqY4t1SsoHd68tA==,type:str]
    ADMIN_PASSWORD: ENC[AES256_GCM,data:k5id1qI3LWNZT00Qtw==,iv:F8+JhMR9vDk9a5cleRXRmWVWiuQf/i1q9UAlQre2xck=,tag:JFGb/f/agJFXk3FrprAPFg==,type:str]
    FRONTEND_URL: ENC[AES256_GCM,data:sOp7hibsnAi9tIyirXmUB/DmmYA68swMkpDL,iv:MUAdTdbh9031ALkG2D2D6GAlEf5/rEyuX4qy/Pf9Y84=,tag:EP0foBxWm7wpoIMtLTA1YQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wy58yxmfdehpfyzwkw3kvqfkv0ze65lyf6yuhe5xt5n6md0vhyssnqkf2t
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtOGJ6cFYrMDBzVG5EZlo4
            d3ZIeEQyaE84Z2xFL2c2Ylo0NklQZXI1aFVvCnM2TFV0Q3ZLZjE1d0IwS0phMlF0
            eWFoakZ3WWZzbHYxQTdaTXhFMEUxM1kKLS0tIGRmdU8vN05NZ3B0b2ZnMFRBakxh
            ZFhGUTRCNEtDME9LY0lZbEUzWTNtVTQKFGGnW/tLx0WfIN5+xD34sC5J9lqsceZM
            QwwZdqhLB0jvX90CjBOzldHXqx92I5s+GweZ1ZMyoh2vc5BSdQKeyg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-04T23:06:34Z"
    mac: ENC[AES256_GCM,data:j+U7cT2oUFtggMIwLamSAD7TN5IrrVa+XAcHrK/J01dZTegB054HH/qTnL/GK3lF9Fa3ogJfD04aAJVva8HN3F7G5ORfgr8DL4nudknjaPzwVD6rn9I8kvT41k7gkFKbFArfEyJfZ6yJMqdaxJzY9+zngUjwmbSgOhigZX4t1cQ=,iv:S7/m8cEav3/ETf/UojjjRdmVAA5cbt1Gv2gOZXWAx6c=,tag:6RF3YdBLFFdlnjE25fXpVQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
