apiVersion: v1
kind: Secret
metadata:
    name: redis-creds
    namespace: nethub
type: Opaque
stringData:
    REDIS_PASSWORD: ENC[AES256_GCM,data:pTfsX+l9UQWaGnQHZ9/EE68IOPXzkZtCWioN,iv:8hOwSLcbhl0zPHAhOEbzqZ6OA1VX93Gn+FbRdUWYk9g=,tag:13yp+Jpgvv34OyKL4wvDLw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wy58yxmfdehpfyzwkw3kvqfkv0ze65lyf6yuhe5xt5n6md0vhyssnqkf2t
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxV3U5NmpDbEtoTFE3QUtH
            ZjJSV1pvaVorci9UVTlEUlRZRk44UG96dHo4CmVZVHliSlM2Z3prdWxQTXdSc1Jv
            bE5zcXB5bW43ajk2b05yQWh5dGpya00KLS0tIEVOdWQ4dURKa3dVUzFDNXdZcHlr
            YkUvUjNrS3ZrOEdFZDJmRGtXZjFIK2cKuzaeXnC3zRPPsxzv5JsJ3G2LmMKOZ+Ds
            1w96kiG07ub9GEjq7ur2wSfLXJJOyk6ArSFMnslDByT+tjZJguX9QQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-08T13:57:21Z"
    mac: ENC[AES256_GCM,data:FscpK2ur9EyUVdeGkomznUPUC5YaTJsuJqpz/Ha01REcoHjNfQQXp5Ckxe54EKmDFXblTpy+nTgw2RarpXGaAN47vC7imsUGbbHTRguQAgT3Y+jU2YIrfXKIgFGKLHPPy6WHITYJ4cHI+aycZ6eEtCkjb48/dEs0GltoBzO0mYA=,iv:CY1ujFCYVlDCJa+eGc4V5Ir5OE8+IspXYiXw5y+upug=,tag:naL3JVsRmDSW61Qd4uFyWw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
