apiVersion: v1
kind: Secret
metadata:
    name: example-app-secrets
    namespace: example-app
type: Opaque
stringData:
    EXAMPLE_API_KEY: ENC[AES256_GCM,data:f+suKhnTcm+eZC8PLhNDmJuE0iWkkFT2m1Q=,iv:Qghe7XDUZlihgtahBX7/lhdbnHTgAbiAx6i0L9KR8sI=,tag:x1e5fFpRP83fmDvXJX9OKw==,type:str]
    EXAMPLE_DB_URL: ENC[AES256_GCM,data:b8asoATNgu6NnC5pp9WHuD8mSIRKVTT61t126658mwmkzarF,iv:CZaeEzdDGy2LmHnuf4UtIclQogkaK6B8aIdNiKKENUE=,tag:pstoU3SA3XahHEFHv8dC5Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wy58yxmfdehpfyzwkw3kvqfkv0ze65lyf6yuhe5xt5n6md0vhyssnqkf2t
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhSlU3WWVXZ0Joemo0UWxO
            Um13V1I3Rytlc05jc3lSN1VzTGpsSk5JTWxjCkM4ZDdjSmlJNmF4NUZmbU5uSks4
            QXhxQkN2bFVvd2lIQ0p2eEZGWlEzZ1kKLS0tIENFbGNtNU5BcXg5eHNSTVFBbVlK
            SEhBTFFsNjZVSlJ0RGVzMVFCRkJjbEUKwUoYfuNLsRVWWz0pEZWjEugH9lMEGm8P
            D0YLMI6e3+rJ+lcfROj7YraTppnggs+Y8DNC5xPlLblJMxlPlQaGjg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-01T12:41:52Z"
    mac: ENC[AES256_GCM,data:XEyQHf5kw6ITRtGQZW/dq6+KyDVLrctoUvUNsDzMBTX94Avhs3WOziN/O7Gwt/+46FGCdTGQ5MOygbysdsCpvE10zRFItIoKAoq9g/0/JHZ/wq399QzeHu0vy6vUvxa7lHqXtoQI6U8T72pBHHjcP/atbxuCdRZe6zhE2Q9SVuo=,iv:ytwfLcK0Yc+IK70JZbBmMnhkNviW//uwjFqKBKqOWj0=,tag:4NAPk5lWg0Ctohl+t31frA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
