apiVersion: v1
kind: Secret
metadata:
    name: keycloak-secrets
    namespace: nethub
type: Opaque
stringData:
    #ENC[AES256_GCM,data:i/WMmtiyMDQJ5m1vrcuqEUOJXwDxGxvHfamfMIUDyNZsRMhKMvpYByxrY21eOpwthFYjX6EWLHkk6Aw11+g=,iv:2UrglFE1YA1yXdbJ1B3kowDwsUOd3AP8DFJuqx84YF4=,tag:l31vOxt2okxmN1PVVBgU5Q==,type:comment]
    KC_DB_USERNAME: ENC[AES256_GCM,data:mPL0gaheDhI7L6xF,iv:fJYNfjvwOhcQAA9YZSbtQtigRACwgyyPeOCYIU0VMZo=,tag:YLI6aTMjI5rXbNJem3bvPw==,type:str]
    KC_DB_PASSWORD: ENC[AES256_GCM,data:gMAbe1EyR2PlgxpGGO49H9TVGwM/Lg==,iv:z2fLBww06Frd2q8/2Y49PLouDQSCCuRcOGfgkNMIeSQ=,tag:V+XitQ/ZqpFKmaBplIi60A==,type:str]
    KC_BOOTSTRAP_ADMIN_USERNAME: ENC[AES256_GCM,data:nGb/LXcXdnc=,iv:TmCkNqoNYqVb2I8oXq38x4bu+TzOQZu0JuDgU9TrVAk=,tag:uagZH/cbNiOvgYzho+KKjw==,type:str]
    KC_BOOTSTRAP_ADMIN_PASSWORD: ENC[AES256_GCM,data:aDOtfLaEf7XL,iv:rX+oeIGuPVPWvS3uIFfZRqbxJQvHeeyUDB0idIsu03M=,tag:FtUymtLZeogvczREq3wMbg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wy58yxmfdehpfyzwkw3kvqfkv0ze65lyf6yuhe5xt5n6md0vhyssnqkf2t
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0STd0L3BUYkdxNHVpdmRP
            aDFMVGJyMjVFTHNXdjZoREpYZ1pYQ3dJL1dBCmZpNjl1M2ZVZWtoRXg2UTVzc1lC
            NUgzYUhKazgvUXZRZGJ4TDNENXFxNk0KLS0tIFByUzZmWXFoWmUxODFDM0o2QnpJ
            dHZ0TlZLVEw5MFROMTRkbGtKZk1xRTgK5nUAAfZ6TYDBLrfkvhcmauMy9A2b5KbH
            wNv7ZVwv5HTbdflNFW27KlyL6A2cohCIgaCU6Ud0i1Itc5YxYqbRrg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-07T22:21:10Z"
    mac: ENC[AES256_GCM,data:x8WoQZqChTQ9zl5ljZgxoH5ZiutPXcsGynp0uwhQUik6at0cRvlPEPgEuwsG9g8kedXZMq1coST3amNlQD3ocSliui7SVUTaMnwM9mFKk+dPsdsb42aWF4iOz/K8xWidlHm8ONdhhZWaTwgbtgDIHksawu1kgd+ZDzEU30rgMfI=,iv:3Uo0/K8S19hfxYAl62M79Rz+mAeKSNHDH1qx2YkspWA=,tag:GNrL5s70vIb1QnvkloVwvA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
