apiVersion: v1
kind: Secret
metadata:
    name: nethub-api-secrets
    namespace: nethub
type: Opaque
stringData:
    #ENC[AES256_GCM,data:ybXgqfrptTpo1tfl27dHxDcrEG/GtLcu+99+7UFxts3JgSagvLserdmy3YROh4DS1Z7ny6VqiIourKUOrQ==,iv:IRZ0d/cJ0Lk2EOVT51YvQWuBh78Y6MZ4XSQBFbfXtEg=,tag:zjCKP2Dvr5ThyzeZC0OEAQ==,type:comment]
    ENVIRONMENT: ENC[AES256_GCM,data:f48r0RnoFmyB8g==,iv:D8TaLCx5vu8dQT1jfQsltKgzjnzjg7k4IZb1nFGqhIA=,tag:zkM/Jb0t/VoV+gS4POPMuQ==,type:str]
    STARTUP_TEST: ENC[AES256_GCM,data:ouEF/Lc=,iv:GZ83DObagia1mYTHe4qP1rzMQMQMT3LK011Noo22bhg=,tag:QTVyjwpLqbjpljt7YOZ24w==,type:str]
    APP_NAME: ENC[AES256_GCM,data:Q9jFvept0W4gy73w,iv:g4i00SXdTwfI/qjTe8LENrz6lzgC1gNAheXpEwti6M8=,tag:QahF8su9rC7657B86jCHLg==,type:str]
    APP_VERSION: ENC[AES256_GCM,data:JVD5bWQ=,iv:aHF25fbBjj5IZ4ie4qBi086BIong73kHmBLFRR+NwIk=,tag:LbpdqMLs7wtQreTk5aX78w==,type:str]
    IMAGE_TAG: ENC[AES256_GCM,data:EUbTBpJK,iv:ysOahxWRsBpMYgdJ766IweZKnaaOZcimMu1DY/tb1L8=,tag:+DWmjMTEUBQx8/ZU64k/2w==,type:str]
    ALLOWED_ORIGINS: ENC[AES256_GCM,data:cNXHGf1NpfVNq86SKiBZHDco+cuCpKRbHF41hQYRKFPq2Qv40Vm1ZjqGuItbsR2xvtHyPeKU8hgtohb67zspnvOj,iv:vPQdWUFYvw2qYlJKAy3aZKfvMPTwB3swpfCBN+aqVBY=,tag:6DYIPyl46IA5H+ornLA3HA==,type:str]
    #ENC[AES256_GCM,data:Elsq1yMzlKHqgMVga/60LyA=,iv:1b8k1x50C6OH21OEV+d5T6PX7U5ka5bmzQDSIOOQcJM=,tag:4FwW/xx8lIDgy0EzKmUckg==,type:comment]
    #ENC[AES256_GCM,data:9CiYbLWTKgZ6uRoFlQaZFDlZRhoY5xGFoRWotvC0uaGEijCqFw18jl5T6Zg2ChWgixQe6xMk+0ccrylS690=,iv:N86agWR+nluWPlQEI4fQ6dVwv2VqvT9lLxsDmDs7vw4=,tag:5RAmkDrezVrZ5MIffbN4bg==,type:comment]
    FASTAPI_DB_NAME: ENC[AES256_GCM,data:9gD5Du/rh5Le,iv:WpwmGZUY8zJ2wE5fLP+BefFwpeLBUiwVjR6NaDTx0ZQ=,tag:eVkiYRWvK2MSzcUKwBu39Q==,type:str]
    FASTAPI_DB_HOST: ENC[AES256_GCM,data:CpZpSzkLQUFktq22Y1OFq0qt0ZcQQW17xSg7d5s5hh2NliYsM0hKWxvDWg==,iv:0L5UrlVBuc+Yb0XPbF0hHa8bwluIIeDrh1iPHaf7c0M=,tag:15AP8yHUKyIABSO3tJJXXw==,type:str]
    FASTAPI_DB_PORT: ENC[AES256_GCM,data:sRxHmw==,iv:SsA5Jcx61sP/9g+v8S56fQrvX6R8hZzhQ2idI4Qkc9A=,tag:Uf5EwekaliOdCcMdtnEaJA==,type:str]
    FASTAPI_DB_USER: ENC[AES256_GCM,data:BCoiLDBLRDgPQOeZ,iv:hr4lcSd+0Vm2ylgS4xOae3hdXjdUOxkLicrOXZrclmo=,tag:FZyGouQCRiuZFAKejX92Lg==,type:str]
    FASTAPI_DB_PASSWORD: ENC[AES256_GCM,data:peC2P/NOZvcecGGvzxUyLyZb9it+AQ==,iv:5cUwGbxBqXJnpy4zXusOBZpmZkjQb+iBy8Ph+0NO1c8=,tag:Z/n1BE8Ex59pnFkodon2aQ==,type:str]
    #ENC[AES256_GCM,data:upAfeP7L1BkvSFN4kJkjnPGWBQ==,iv:rhqG25Q3Iiig2uxABrve80Z04hJe+vOA1zr1qELMi8M=,tag:38Tp6OEH7dUq6AHM47s2eg==,type:comment]
    OIDC_ISSUER: ENC[AES256_GCM,data:0HS0U6CZe3kkquZWBh6rVwIvGG7uM1eWPw==,iv:wZsmw+Jk7GFXbYM9OCVbxEwJaIGOyRZ7GnuLCxdlJI4=,tag:/h+rcuNXR3ilFCT92hQX9Q==,type:str]
    OIDC_JWKS_URL: ENC[AES256_GCM,data:xp3mahk9pZjfeH5AwM3Zu6re+XkMGXvHeIpFYTOBUXzNT0WtCzLc,iv:7K2VnmVB9yPxYo9/B45IkbAGX6cjIbh0Hc74iTuO2RU=,tag:x4pxVe7DjvJPYcTKIVq+7A==,type:str]
    AUDIENCE: ENC[AES256_GCM,data:a3KtkX0/8sf6TfUIQZBf0JPF,iv:8Eg/coNI1aAiAR2Rj1ExOLZcYVOjuLjEhuPj09a/GEE=,tag:6+97NBlUuYwiJ2M4D+quFg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wy58yxmfdehpfyzwkw3kvqfkv0ze65lyf6yuhe5xt5n6md0vhyssnqkf2t
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3VUdsK3F1eFhkUGR1UjJl
            Yjk2QkdtSTRGZHZtdSs2OWh0ajd4OHlkM2lBCmtUMjZDUzdCK2ZkUzhSdU85dkh4
            VjRTMk5aWkVLQnBDM1dsb0tvM0VTc3MKLS0tIGJYM25wcGFnMUJUeGtuR1EzOTlY
            UGRXK1RTY3pPNDlDS0lLTkQ1bTR6NlkKFA9Z+ulTROklpLzmGkNOJl7TUnv2pTqK
            Z+v0uGtlyrrV3L6OQTgIoiDRwxwH85QnEM/Wql25HrKIkr94jpqMJA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-10-03T23:00:38Z"
    mac: ENC[AES256_GCM,data:E0eQqNQkP7lnuu057UmeHd2PoHirweH5vcJbwYDSvY2GJKoWLI8R0XiHwzbKPEA1NJUkhzynblabGAht4v+GnU/0OWZ4iA7BXoREiSQ21rZHUCx/Qrd0iHq9K35N0RBuUMYYrOKEB4jYIM5gya085z6hJAnD4GaVSwe+UVa1PLg=,iv:2V1AJ9wYbESDjzrvtj1CovudHuaGTnuw80FliVHIkGM=,tag:w4+nSDP17txkwhDXBd7TgA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
