apiVersion: v1
kind: Secret
metadata:
    name: netpay-secrets
    namespace: nethub
    labels:
        app.kubernetes.io/name: netpay
        app.kubernetes.io/part-of: netpay
        nethub.co.ke/purpose: netpay-app-secrets
type: Opaque
stringData:
    ENVIRONMENT: ENC[AES256_GCM,data:tzRnKtSuxswIfg==,iv:3GeM4KDAaZNEOXn4wZ1sf3un5Jc4O4SV1Rp1+DGdOAQ=,tag:wdPI9T+STsiRmXs0xNS5HA==,type:str]
    SECRET_KEY: ENC[AES256_GCM,data:61pY1iGbRK6kuliBpOjiYfF+/ZM/aytHSKA10Ty0aETvKkmz3AgBOJYPBhhR+fAsZ4ieOWo2EINgRoE7Q2PCiw==,iv:VbYdt2c9R66XUkp7CCSFN9cRoyu72/LN3XnS7qqLUoQ=,tag:O6+mKwrx1g3kNNfdT1+Eqg==,type:str]
    INTERNAL_API_KEY: ENC[AES256_GCM,data:e4YEH2U4Yj2NzMe4vPAckdgFAgKHSK2OJN7maDfdATN4Iv/Ut+UE44Usw7m8TuXx,iv:9MUa2vxiiBy241amzMpco4eVf/CLiMCl/H0YS7RKe2c=,tag:DCkjw2e0mooHYOid9B0PRg==,type:str]
    REDIS_REQUIRED: ENC[AES256_GCM,data:PFf23w==,iv:WddlwsSo0kPrQJLV+et71dtUd5vpNq26tW+u/RSni6c=,tag:WFYO6WrFg5J7aEgBU6ZNoQ==,type:str]
    #ENC[AES256_GCM,data:CLiE6d44YHpT8MBQCRNNg48SPbB7QfZ698b21ykb8iAUlJCCv7metM1DfEcw23d2XcYHBVI/03qD5+JryAN/DjdF,iv:JDGRlkVV1hWFD2VHARnqgdOhg240MpPqr+fHjE+tp+E=,tag:VmqxxNSqG8HPRCUxQpDqZQ==,type:comment]
    #ENC[AES256_GCM,data:DKWu/MeTOHABrlRxbQLEft4ynZyHmKIG3jwBzSd2q2lq6RzUpIruOeQNTCHlG6mGrYfwG5In1v0WgeYhDtPjZpLIE9fvnORksRer161VnkyMQXpJ9u/CIm8x2o4gTCfueLthTpU43gyV7b5X9V9MvKA=,iv:KkkZ5+r9XhpTVvWP650Yg6onLI6QHMUAalIzjkR7C6g=,tag:wgPAGuH/vOX4Itu7BPR0hw==,type:comment]
    DATABASE_URL: ENC[AES256_GCM,data:oVmLpKOEv0BPMeAUlJdmyM0mEoppKtu4ZjyB9davshRSmis8A9TVNjkpcq8vhwtySiixonhbkOTyIOgCd8EBfBqVra4MwLCTlhfiaPumJurtkkHm9rN8dZYQtieYwX4fQ6QM15874OrSN0uClww=,iv:MJGac10+2rJOGFleUG/9DtNCVeonliduXaID5ZFYt6I=,tag:+88f5JRGU8PS8xxmr6kmPA==,type:str]
    #ENC[AES256_GCM,data:jxz9kl62M+dxoICml2Nz90/zpf7LAnQy52gO1zIrnHuQ8vix2o9QFXros/K6NxcJQm64Tms4,iv:O5F3JHJqxsjBpNLIyXlEca2F2wwpwgsOaAYQeFDw3Fw=,tag:DgNRKRPcN32h07uOx27F/Q==,type:comment]
    REDIS_URL: ENC[AES256_GCM,data:/8gZvNoNjYBkNhFY08MnASp6zXI5YMbq6gFZG+HqbYQxyWqufcbsMQV04k2khx9O8+AeGBc=,iv:ZVUV/6YpsOoxBMrfisNJaK/NwE8ZWvnwnZnIyjSKLM0=,tag:0OlNKifXl0ZJ6V44G9jeLQ==,type:str]
    NETHUB_API_BASE_URL: ENC[AES256_GCM,data:Gxi+q+eZuUW8j3rjT08qXp02WaJ2HHvn,iv:D9aZfG1ZVFUqNae6nq1ZFz3D+MU8cl188RaZyBxyGDA=,tag:d4HiRo/7Z6wFHwmmRbfJBw==,type:str]
    NETHUB_API_TIMEOUT_SECONDS: ENC[AES256_GCM,data:5g==,iv:Th8Ox+BD0ZI6x+4icxKyi2E1J0am0jnSc1PG8sEroW4=,tag:LeC2ibvBqXwhT3XWr/rsDQ==,type:str]
    ADMIN_EMAIL: ENC[AES256_GCM,data:yCaUQ++Va+KI5LtxyJqqOevG,iv:Fo5xBqzSGTuygK2qteJrdluA7uklSRlbghglbunetHw=,tag:dMM0NCRHiLCoa8pGZHs6qw==,type:str]
    ADMIN_EMAILS: ""
    EDGE_PUBLIC_BASE_URL: ENC[AES256_GCM,data:rM5S+0lHi3bJTj7JuRa+kNEiS2GOttVhVQ6rAg==,iv:Lx7Jw5yklIc/Y1EgGI/BAoVNJt+bEHRlt618kFQMnbM=,tag:zD/f01MRuXCPHXgqG1Y6vg==,type:str]
    EDGE_CALLBACK_PATH_PREFIX: ENC[AES256_GCM,data:nneI,iv:xN1VOFQB6+XKLzBV/ekaxX3vOR2cuzOVDqlS5lEyC5c=,tag:gjELDhSbAaJYn4ZEYftFxA==,type:str]
    #ENC[AES256_GCM,data:hxvxPCootS9JOhBxn0sUK4aPZaJ8woiOlC3qqR9yoqEwwYBSc7YCXF+/HFHWAYD1Mk3a5fLhLHjh7tG3hKZJsN2UFcw+WV7XoA==,iv:Nqq8dogaW54gNrG6HXBlAlkrMJvE+Gr1lH0evCXL74w=,tag:lZRYNpffiLab/x+OORgm3g==,type:comment]
    OIDC_ISSUER: ENC[AES256_GCM,data:6UijtiyLdCFTc2XutTBBcrr2SPuJxDdoyg==,iv:edLZAJbPz0HADa0HcfCXkm4tVoHVNJE2KBgTor1giAM=,tag:6ZVCJMZ5qdgULIskyhdbMQ==,type:str]
    OIDC_CLIENT_ID: ENC[AES256_GCM,data:EkAGzDHbCPHeWtE1caDbL+MOWgRzYBc2mhoVEw==,iv:8JQXaPfwpkQ3qXdsF/ip1MWnFPcwxwlB5W6rp8qprvU=,tag:gcIo6eaB47AaawmqqXQRaQ==,type:str]
    OIDC_REDIRECT_URI: ENC[AES256_GCM,data:91pxkg8ObalPXYvYVbxNw3M1R3sKL/jVya9RmOh9hA8ClDtG/iU=,iv:rn4wAT7+XMkuwc00aZAyTsFJUZkWUtLPJhnN5ysrL3E=,tag:HJgjwwkDu47IzxSvG4zPuQ==,type:str]
    OIDC_SCOPES: ENC[AES256_GCM,data:t8Z7Lueckto3GAsAZtDbf3pmr0GAhHrq5nEO54Yn5gfVy1M=,iv:B+avzMXdMiT4VFkUC0Jv/3IpwW//wYNwAxVDHz896m0=,tag:uX3sGce5kaKUJWTOib7m0Q==,type:str]
    CORS_ORIGINS: ENC[AES256_GCM,data:bSRbjeQS/pZ+xj88looHJB/3mmnanfQr,iv:+Jngxgg6QEvnHy8zdRB8Lm1ByPzieqYcFgrzjLc60ew=,tag:TuITI/dbcYxskzw8LPQ+fQ==,type:str]
    LOG_LEVEL: ENC[AES256_GCM,data:D+6KsA==,iv:aBjqM8FgCO6wlEPY55Lecubr1qGgW3wFAWApZ0dA5H0=,tag:Hx3HT/MsyTQf/QcusWTn8g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wy58yxmfdehpfyzwkw3kvqfkv0ze65lyf6yuhe5xt5n6md0vhyssnqkf2t
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNdjZLSzVDNjJRd29DcXQ3
            OTJQRldJWDdJWTFMSnQ3ZXUwcktXTi9tNm1VCkx4VU43dkFQTWNDSUNuWE5CcVR6
            RjQ1SDFYYVNPMjF4QXBUOEJJVitlSlEKLS0tIEdIY2JmVVpyUFpiNEpYNVh1ODJR
            OHlScll5Y2hrSEM5SmJ4TVhDTFRTUGcK21Krl0FSR9pn4wa3pUBn2jqT9z0cfFEG
            2iQEIMfVthk3m7jv/qx/l0ew8DLoHkp7tK59ceWYHO9ODTJekZrXjQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-10-09T10:11:20Z"
    mac: ENC[AES256_GCM,data:U1BOUPq7rMr5FsHImTz5LJzsnayV1KifT3moVYSoTgQ1sJZwd1BlpCG3+rrCQNQH9L5Q1pcennaNtEZnp9RiC243YqLzhPlFBHQN9Zz/zsPikNgU+/jXlCJBX+SgekTj0gdlzFE6fM6vp2WjVT+cQuKfVIw1opAjV1Ziwd8l3rs=,iv:TGaMkHsmdwgCxNM33WC0ayq9pkSgTjLEm5u2hOcHRNU=,tag:OIisbXcvWKixRVMziT3Hcw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
