apiVersion: v1
kind: Secret
metadata:
    name: netpay-secrets
    namespace: nethub
    labels:
        app.kubernetes.io/name: netpay
        app.kubernetes.io/part-of: netpay
        nethub.co.ke/purpose: netpay-app-secrets
type: Opaque
stringData:
    ENVIRONMENT: ENC[AES256_GCM,data:pF426/FE368jxw==,iv:MF8qI45z0hZgG+0EcRKwK9RH+dNzLoNDFq5cQ8ORcb0=,tag:SMYvTsdGTwren/ed12fLmg==,type:str]
    SECRET_KEY: ENC[AES256_GCM,data:hilvDwSNt+D18zARzVtCaIaNLSMVyZje0gv+wOPPTJJao+gY2RwnwvLkZoee1sh1iD3z0Lq53Iu/TmM+5yktkw==,iv:9nfzYAE0kKiVaUtKjjF3xyUI8lkh/9pI3TkbB5xOSAQ=,tag:Tjz/ar86zw71oOkD8KNsDg==,type:str]
    INTERNAL_API_KEY: ENC[AES256_GCM,data:DEySa6LkWe2OhcmDhFTglc9FixE2/v9ChTzG3W3kVh+dPuxGLmZDpWJ3KYXdt4Rq,iv:noHCIm+u0EYje3pR/AJWtj/tslBRozFWHICY4Oaw2CE=,tag:iyClKyqDmWhOCEwZottDMw==,type:str]
    REDIS_REQUIRED: ENC[AES256_GCM,data:vQFx7g==,iv:51p2Ck0FxeBw/aAB9D8NNGsIr3m8i/SEwpjAW5OWaks=,tag:0ebU6Ic+64h1m69Bg7g7Ow==,type:str]
    DATABASE_URL: ENC[AES256_GCM,data:OhbOhMz5XMCcRmVO4kt9dMhBal+jUG+LRQvlqN33sKuQtBprcSOW2CaKV1sXZ8s4/mDLyZMtXoRCSZf3bA5B9Z/RXxPZXkH7DAT6i7AChqSHQZipcra2UFMkJ5VUeR7QdZng6HckqGj0nHXN+HJk1g==,iv:JZjEe+ZN145pNnxwytAmHzErOTlnJXI9j5+3+FW5+2U=,tag:CaFFuxORpgMmJFkuHAr8mA==,type:str]
    NETHUB_API_BASE_URL: ENC[AES256_GCM,data:Ma66X0GX6hahIRmxs08VHRIjf1UY9qaP,iv:9UiHQ2ahrREGLxdxcL0z/fCnCavh+vcSytJnnvhq+yA=,tag:xVoW9LZ+3BJRk0KI+mqfdA==,type:str]
    NETHUB_API_TIMEOUT_SECONDS: ENC[AES256_GCM,data:YQ==,iv:KLyKDPkJCcBiWmF6uKVYS7kwZLdgVMciNG/uqALM17Y=,tag:sKN96uz09ecMDfernxubkw==,type:str]
    ADMIN_EMAIL: ENC[AES256_GCM,data:eoDaJ3toigVZRjtYBt1r8stQ,iv:D4vjGaRUswZSRgABrq6mUQ1dT0Irk7QPW/6DAJ13Axk=,tag:0Mc4DrE0mhv+2BIOQZXDoQ==,type:str]
    ADMIN_EMAILS: ""
    EDGE_PUBLIC_BASE_URL: ENC[AES256_GCM,data:/d/vF7/0adaG/KooIbbwUZCIZMm00rUySPT/XQ==,iv:+MGjQHGS34jeJv6TO9vk+whzcTx2PijXMvBQ1cK3blU=,tag:+DZm1uMCW6tN2RFsB00fyg==,type:str]
    EDGE_CALLBACK_PATH_PREFIX: ENC[AES256_GCM,data:qnBI,iv:Nzye9bVlBtzxdc5UOQkWUUY40BMT3WQRjZabnS5wBfc=,tag:1reMKhCP+93PXi6T4/FPVw==,type:str]
    OIDC_ISSUER: ENC[AES256_GCM,data:St0pQFCS5fgQ9JTcCuOxkEuiU14XJNIssQ==,iv:Ce09JPoBblI+xcjkPPo/02xhBXPfCGLGMVgFqdFx8Wo=,tag:V0kuFSMRdMruVhXFA1yw9Q==,type:str]
    OIDC_CLIENT_ID: ENC[AES256_GCM,data:UuJY8po2KvJw3RtF6lWZGqn6PoBCtBmsTWG9CQ==,iv:EM5CvMkBLmBe57aMxreV0hLjfdAriL0XsHuljYT3yDo=,tag:bdhvm13i6mjpd53mzygkpQ==,type:str]
    OIDC_REDIRECT_URI: ENC[AES256_GCM,data:MEk4jyQI9sjs4oEcHdUYh1nHqd5NjCkVrbn5RFwQPT36wVoVa70=,iv:veejCJWEjXWn62S/2cNv2YH8mNeFFhiMRLEkP+lpb/g=,tag:A1ZzYEihpPmGtMcRzM6crQ==,type:str]
    OIDC_SCOPES: ENC[AES256_GCM,data:TO/pq15QqAWv4xDLG8LQPYQJ5eM26HYmTXajbW4+STD5Cgo=,iv:IJxvqdEnYfKsKPEJDWhdEC55DBUhfunITm/71HlJJB0=,tag:gkN0Bm1sv7vDc36FqFCvgw==,type:str]
    CORS_ORIGINS: ENC[AES256_GCM,data:kuNSdRMolai53ZD6HzaGTFOlS7FFjh/+,iv:GwNZl0MNUBI7PmijFstB04lacIf4EZ7WYD5Ho1qDrcw=,tag:MtUsknokV7QC8f6Jn892Bw==,type:str]
    LOG_LEVEL: ENC[AES256_GCM,data:sx429Q==,iv:TA43eTZIh59mxm2sqcnhSCF8BU7K/oc/EwVxLaNBgak=,tag:by1yvcejuZxOsVDRY9LjXg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wy58yxmfdehpfyzwkw3kvqfkv0ze65lyf6yuhe5xt5n6md0vhyssnqkf2t
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3TVRSQytVZ3FpbFJmL1ZB
            dk9VQjNHMWplc3B1RHJhMDJtZm9MQVcvWjBvClJOS1EzbHhXcUYrV0Rnb0RpWGZt
            Tkh1RmxYdlJxcjVGalMyZHpuaFhlb0UKLS0tIGQxajhYQklFVHI0M0JpTVNUQnRF
            U1dUTEV3dDJqT2Q0Q0M1NjRvdS9qK0EKyug1iWdOJ8ALe7NsC1zBKX5BAf1i4LsM
            YG3YymGVbXzJ75QtlsixtVfxs2m/zrS9eVHj7HaLvacgx1UVGfmsvw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-10-09T11:04:21Z"
    mac: ENC[AES256_GCM,data:CJHQUxhktj3nXxqKfi8Y9nGocnOL+CTlXzJ1IBtX0kVJ/NpgXmB4fp7QCSfeVZ9anQ6XSsShXRitdk3VNdVrFeTBt1u9xDnb0GbazQe3tc82US37PrJejQpsnncaiSDPhREauSVm/Rd4VjrG3jbNIFdAPFXeaEhDIe1y7F5pYTs=,iv:1nhLX/nuYovvavLlHgHW9FX63fUh2n9hP83KaOcMbvw=,tag:A1FGCfuuusqGICmTyXKNYg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
