apiVersion: v1
kind: Secret
metadata:
    name: zitadel-redis-cache
    namespace: nethub
    labels:
        app.kubernetes.io/name: zitadel
        nethub.co.ke/purpose: zitadel-redis-cache
type: Opaque
stringData:
    #ENC[AES256_GCM,data:VFsoCFH39+HrT5GHShoVxSIGYH0mnONEINJVo+mq+rIvG1hVphkQZoefAcb5O8DLr3dMQTwzydMSwX1WXC0lDS3W4gW1,iv:GsjU28abFNrBMZ1L8XsIG7Qoqo3QyxkFtdJBciKdlAI=,tag:6ZaMS9EhNgvME1TOPel0cA==,type:comment]
    url: ENC[AES256_GCM,data:w0t2Pw+oRbxNPkZineDtUstJgUXKvGXIqIcC864SaSNlzAkp57vBB4Jy45sPRa+UUELzNWPMOxWIOXXtAhBFrx5a3yE8e5LSTwGEcLOYW/wJ1Fpo+sIKE0lymdo=,iv:u5NDVHoxpQ5pXzcjzGFFNpyFxOQUUFNH/oGaTh94jjk=,tag:lNCUY+W+ismRMcV1fKb2/Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wy58yxmfdehpfyzwkw3kvqfkv0ze65lyf6yuhe5xt5n6md0vhyssnqkf2t
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0RU54OEFuMVoyMXpaZitM
            bnl2UlJnYWt5Wk5ud0dXbDdJRWdNeWJlMFRNCjVtV21jc0hFcFQ0Qk8xU3pwNGQx
            a2NDcVd4QnVZZ0hWZHJQZE1qUklvMm8KLS0tIHl3d3gwVUQ3UzBMdGo1d0Q0OXVG
            L2pSN1B4NTVnRzhOY21KY1h6eHVYU0EKUMplUVo70WqUz8cifDrJhW0fQ1gi7+tB
            hxz18OHXFraAICUpUUwvq206h14X8jGFZL1FANVbbqjadbNV8pv54A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-30T11:19:17Z"
    mac: ENC[AES256_GCM,data:pU0Tkf4hB50NyTCZbAzU4ZLC1L2oxdEWf3Ljy3skrRw9Em/12L7h64WOJ2xQUW2DcR4v9558P8xRSpJXiyuE7eLlxSDRcLrE87cBs6bzKAS6ZGr4aY6y0vnLJ9Ift4jA02vYQCPkmNKY58zgArX2jBs/WYR4qUQbTadG4L+idcs=,iv:BzmRO8NWL/avAjJwT5mnKfKosR3EFzMdLiXg9/8Us7g=,tag:0ngCGYmyhm2aSIb9Pa5pWg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
