apiVersion: v1
kind: Secret
metadata:
    name: zitadel-secrets
    namespace: nethub
    labels:
        app.kubernetes.io/name: zitadel
        app.kubernetes.io/part-of: nethub
type: Opaque
stringData:
    masterkey: ENC[AES256_GCM,data:Mm6xNxUaVRtw/o0Htv2OOCYn5KHMyOvxLPZG5KCn52g=,iv:8XF+AX8qU6gibQH/Pk9AzRNF3Sgnq3icKw+byx0ToHw=,tag:s91SbEcof/H3dhXjcoSSug==,type:str]
    ZITADEL_MASTERKEY: ENC[AES256_GCM,data:5sOGHGXR3St9cNi80cIgRizGaRf1UBDk6eEeGaIhzzQ=,iv:CpkpSkuALnJGIZYWk5xapyY85DRzRFrY+6senbqHv1M=,tag:/Qrrn7SBvklUfK3ibHpYjw==,type:str]
    #ENC[AES256_GCM,data:xuFxglG5ePU+iqe5KiMB8nInR3SD1oC2pSh8yHeUuSX564mWd1qa5CLucg==,iv:6w0xAbgF6OKIJAbp4m8T41jYn2cVxBZi/K1WlbQasZE=,tag:tK6AD7fZPMVIPlbiCSCZrA==,type:comment]
    ZITADEL_FIRSTINSTANCE_ORG_HUMAN_USERNAME: ENC[AES256_GCM,data:38+/sVA=,iv:ORqt4JVXKdlpIjJ4SGboadU8PjyY8oAtC8zhJfNWkfQ=,tag:LnNDt/yOGH1MsvTASmWG/w==,type:str]
    ZITADEL_FIRSTINSTANCE_ORG_HUMAN_FIRSTNAME: ENC[AES256_GCM,data:jxKzYE0=,iv:FZaSyGVyNmricZbS6RSm5bZFpeEoDOy8vReqxbOkhhQ=,tag:uSHW4xtXEnPAlKR3am444g==,type:str]
    ZITADEL_FIRSTINSTANCE_ORG_HUMAN_LASTNAME: ENC[AES256_GCM,data:v9g4d3L2iw==,iv:myqRJpW9zSJQjS6kvWB98y/SJ4Jk/u6g5Pj8Kf9A99w=,tag:xq7PoVoFLSk2QOi/SfvoPw==,type:str]
    ZITADEL_FIRSTINSTANCE_ORG_HUMAN_EMAIL_ADDRESS: ENC[AES256_GCM,data:AukJ/3fSvwXro1hoGhbXZ7KBYL+j,iv:W8cG31nTTKc/J+F4a8QZT2PMybPu+AM3rPM2+HDv2hg=,tag:7o8U13Qpo9XD+DOEYtQ6KQ==,type:str]
    ZITADEL_FIRSTINSTANCE_ORG_HUMAN_EMAIL_VERIFIED: ENC[AES256_GCM,data:AT0p5A==,iv:TQKXlEQO7o9312DqR+aHmsdoeICat/gZQPmMeH6lrRk=,tag:T2ln4TUqmvZB9SECLOKXsQ==,type:str]
    ZITADEL_FIRSTINSTANCE_ORG_HUMAN_PASSWORD: ENC[AES256_GCM,data:8i+82RsvQc8n0cvoBkibKzRu3+gwrR2d,iv:EhmywymVEtKv60PgGl9lwTjjPpxdfrEfAsxIj6i9I+M=,tag:D2tJItN/gCBBdv4RlT6FGg==,type:str]
    ZITADEL_FIRSTINSTANCE_ORG_HUMAN_PASSWORDCHANGEREQUIRED: ENC[AES256_GCM,data:5UkbUFA=,iv:Qn1VXPW9np8M6O+biPMXLy70G7ELnX2972fYMTEL1tQ=,tag:TQClBFArMo9nBH9Fyq3bGQ==,type:str]
    #ENC[AES256_GCM,data:oxiT,iv:n48S/7JNLchQqBVSVzad2rx6upq1xqVeY/IenkGbntk=,tag:GjmfugkVvYCcCi9Mhu7H9Q==,type:comment]
    ZITADEL_DATABASE_POSTGRES_HOST: ENC[AES256_GCM,data:UDHikicN2WrklJBvW9K84VAXC2Sz8d2nHMDqDKVd96FVegJKFhUIe+oJCRThqu8=,iv:CXlwuim9QJ4B5HzGvlWpKhC70jWz+RmC8+atOkk4KGE=,tag:vg4HxoyxONrfQMjw4b59bw==,type:str]
    ZITADEL_DATABASE_POSTGRES_PORT: ENC[AES256_GCM,data:rsY34Q==,iv:ZIEV79OrnzmgUV8yGbB6ukiWMGrOxUsFP68fpCqKTr8=,tag:Dbre3sVMkcWLVPYD6ymwRg==,type:str]
    ZITADEL_DATABASE_POSTGRES_DATABASE: ENC[AES256_GCM,data:RseCxXuBOQ==,iv:C9GSgsRJL+YeCdZIDgceXvGvvmbbk5gEPfromiN1sAo=,tag:0oBM3ufD+zsaCfkwiDppZw==,type:str]
    ZITADEL_DATABASE_POSTGRES_USER_USERNAME: ENC[AES256_GCM,data:sNgC2h2/EIumdF5u,iv:td025hz7OLUTV66eLt7Ak+w8Bg8IEwtsufHlUToWmEk=,tag:wgg+dw7mstjXRzhr6Klghg==,type:str]
    ZITADEL_DATABASE_POSTGRES_USER_PASSWORD: ENC[AES256_GCM,data:OoMNwYQuDfD8ET8rGvtBEabKeUS+5g==,iv:EokoTS4PbIk0enELHndllNwS8m8wZDuZRzdRCjcqJRY=,tag:g3ZEurv3X/j6CIHLwHW3Jw==,type:str]
    ZITADEL_DATABASE_POSTGRES_USER_SSL_MODE: ENC[AES256_GCM,data:3iSquAsYfw==,iv:xqtcaQQtcN1YJB6o6ldiTQQfLxUfTIQAmfbWQ9jnkqc=,tag:MQiIMQDYx0yQiqxN7elTEg==,type:str]
    ZITADEL_DATABASE_POSTGRES_ADMIN_USERNAME: ENC[AES256_GCM,data:DuTsmPuTSVCtZawd,iv:6JUI++fAhBkVqjWlEXCoLBAaPezDhRhCbYknky1fwYo=,tag:iMzjh4fOjYx5ydp47fkSyQ==,type:str]
    ZITADEL_DATABASE_POSTGRES_ADMIN_PASSWORD: ENC[AES256_GCM,data:VqhUFhWIs4I5m7/tzGrYty95WgYnGg==,iv:hLX6oKJpnZZhrO5tKvwzQ416uzz9G9+etkqkKfUEPTc=,tag:ROK6Z0QZi5RtQMJCRzocLA==,type:str]
    ZITADEL_DATABASE_POSTGRES_ADMIN_SSL_MODE: ENC[AES256_GCM,data:LgBppPEOxw==,iv:lmOhTMnMjGqnIGTQDeyD6aO5Aa7Qgh0qWRjykWnMotA=,tag:Je5CEZXZhkYTwinbdNJSVQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wy58yxmfdehpfyzwkw3kvqfkv0ze65lyf6yuhe5xt5n6md0vhyssnqkf2t
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvSmV1MkJQamZkemxzNWlo
            UnQ4MkV1VTdtZnY1b0lYZnExdGVCZXJEckIwCnd0cFJtakhuZkRXNnppNTBUYU9B
            eHpwSkNxN2tPbjFuWFdWcDBQcGh0NncKLS0tIDQ0dW5jVzVtNUgxU2RxRHV1S0tH
            ajh4R3poRkpRWUVyYmlEVThJTGdudDAKnibtGonayEPgpfmXyw+izTFhejFL1hNu
            lUwWwboA+fenNGft+Cgt9ydW6ZXx9PE/bofLaZbyqaEF0uAetjADig==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-29T19:38:45Z"
    mac: ENC[AES256_GCM,data:3nM8e/MlHbJnbcd0dRkSEdBl1Q7J4+Rq0oHwTFJBsH23nBE/HxlBNNs1T0PmoZONisu5SxARPdnUPkhhtuP4jYMdxf9kW+RrQCz/SFp0ILBV9LwqEj/H059iNdT0vAIuXrIhCBcoL8UJHnG2NR5L5KB9io+4hr3ivV7KDsRmanY=,iv:8TxciC21M9Qi5lKNXDg/2NI/XsNbPCIuDsVkwkCql08=,tag:8QcSysPJFosrHTFJMMHm8A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
