apiVersion: v1
kind: Secret
metadata:
    name: zitadel-secrets
    namespace: nethub
    labels:
        app.kubernetes.io/name: zitadel
        app.kubernetes.io/part-of: nethub
type: Opaque
stringData:
    masterkey: ENC[AES256_GCM,data:560OiLmpNJEub7H3YX3WnMSLR3o/hyZJHC6ShLfrWOk=,iv:5M4cEfk2cN/42NRrUE6owHjoSjuJeun5ujYvL3gbEOQ=,tag:do+3KfOLTs+XJYLyXNTbXg==,type:str]
    ZITADEL_MASTERKEY: ENC[AES256_GCM,data:dlt7w4BnR2H+rA6IPfC4J/cRRoyKvvmmc6eeEDIYEic=,iv:CExmxU6Pbxn0EytJMnJASJTINZGjp8H23K42j0uKHj0=,tag:gLO3HaGR3Pb92DUMVnPLBg==,type:str]
    ZITADEL_FIRSTINSTANCE_ORG_HUMAN_USERNAME: ENC[AES256_GCM,data:nXhDUUI=,iv:FajWY7V5kSOI+Tj/zxBl82PtxRS3UdC84Gh8liAO5cc=,tag:JiznT1vL/IgPnaH31+iUAQ==,type:str]
    ZITADEL_FIRSTINSTANCE_ORG_HUMAN_FIRSTNAME: ENC[AES256_GCM,data:6UzYwd0=,iv:ti7MNf+A9kcTIiTS8TzlaQoxH6kv1j4fAys6bCTkXd4=,tag:kJyEoQsNudcEHKx6AUjZ1w==,type:str]
    ZITADEL_FIRSTINSTANCE_ORG_HUMAN_LASTNAME: ENC[AES256_GCM,data:J8F4jWasOQ==,iv:jbHAjeVMAJa6BsLEwG2EGStAk+X5JvDDWxEDu9mGaWo=,tag:gJb9a/Yyw7mhDp0gj/O5FA==,type:str]
    ZITADEL_FIRSTINSTANCE_ORG_HUMAN_EMAIL_ADDRESS: ENC[AES256_GCM,data:l+Eh5ZZfiBRPrO4qWciti0QLbYRV,iv:KMa87ItpJx7l/SUB5htCM/GHsvGlHLXgXg8svJBeii0=,tag:qT4VND4rlDuG3HxR3/LIUw==,type:str]
    ZITADEL_FIRSTINSTANCE_ORG_HUMAN_EMAIL_VERIFIED: ENC[AES256_GCM,data:Dhiq0Q==,iv:B9/DQ2WoP/uxLL0Q7/uWYz7Sy2kQokdlAhmFIzXkhBg=,tag:s2couVSNMc8QfI5cUdBx2g==,type:str]
    ZITADEL_FIRSTINSTANCE_ORG_HUMAN_PASSWORD: ENC[AES256_GCM,data:GIzfg3IyuVw1yLPaxheTFSW3W8C1O9gd,iv:EhvUuK/ScQ/3DvCspCKMWIQvL8rxVZ9mqkDFiWl2+M4=,tag:QYp0xSrOJ4iLZZ+yy2rVLQ==,type:str]
    ZITADEL_FIRSTINSTANCE_ORG_HUMAN_PASSWORDCHANGEREQUIRED: ENC[AES256_GCM,data:tJ3KD5c=,iv:ATZmMDn729+8ccdcpVBe+QbthEy+gv5nyK5NFBTwXYc=,tag:S6MzgW6j6u4LaVITJ1WqHg==,type:str]
    ZITADEL_DATABASE_POSTGRES_HOST: ENC[AES256_GCM,data:craUzob0kKXU9xCEafcRUDH+IlvZvKoOIYhYvtYu/pboEjW+rIoU132T8GqZLpo=,iv:+USCA25G/LvFyIB7atUtwZsTHUX6ppIA9M8FVh3HBic=,tag:o9eQifx4QQAK/caQdU0nLQ==,type:str]
    ZITADEL_DATABASE_POSTGRES_PORT: ENC[AES256_GCM,data:05clgQ==,iv:mDLnOvXGZD6BNNzcOLVY/jVj2ga0HEvYPbn+dDFlvO0=,tag:P3JT0auiC2INlW8nX+KDLw==,type:str]
    ZITADEL_DATABASE_POSTGRES_DATABASE: ENC[AES256_GCM,data:BKNYrIdo9g==,iv:LwhNyfFpfg2htmtBZAosjLs3KQVQcwynlG0dPdz9iZU=,tag:3HwJ5xU3yJQLNsWOP6SdJA==,type:str]
    ZITADEL_DATABASE_POSTGRES_USER_USERNAME: ENC[AES256_GCM,data:Dj44b7LzmOsQlabr,iv:4pKacPRCZmToMq30c25Qvaq356nCQHxi9JX5pUtPQVo=,tag:KenKjHQGWjQ5iPhWYDnIsg==,type:str]
    ZITADEL_DATABASE_POSTGRES_USER_PASSWORD: ENC[AES256_GCM,data:dPZMNKJxZwUOPf8ojNevrcX9/5fb3w==,iv:dOMoTrIn9lVL7y8D1xu7Z0l/VKlA43hSu0hH8nkShoM=,tag:x5zflLNktLDnMJH8s0QSDw==,type:str]
    ZITADEL_DATABASE_POSTGRES_USER_SSL_MODE: ENC[AES256_GCM,data:qkorP8NIWQ==,iv:zYse1NVm+Fk/wJCqoujrKKchofse85Snb7Al4cLRhAI=,tag:VxG1tlbHDXyWPhzJfrkLAQ==,type:str]
    ZITADEL_DATABASE_POSTGRES_ADMIN_USERNAME: ENC[AES256_GCM,data:WFE4olPE6KViasTZ,iv:0BroPub9uZT6MYifNu7ITI2tl5kiZ+NNhWf6bxVYThU=,tag:9AXz4rUumtbngrviPLNvrg==,type:str]
    ZITADEL_DATABASE_POSTGRES_ADMIN_PASSWORD: ENC[AES256_GCM,data:fiyPzK+VnKC/a/fykc3ZjMbKsNM9kg==,iv:ljuNYjuxb67pHZERcArKyrJ6SH7leD7YzPmyBicyS7s=,tag:UZWPkNCrtMoOJ5BZtoC6Jw==,type:str]
    ZITADEL_DATABASE_POSTGRES_ADMIN_SSL_MODE: ENC[AES256_GCM,data:LtwANSpsAw==,iv:v3w14OPD/5U3v93AwenH4RZOVtypQvHEGtiwvcfAgjM=,tag:CEXYdb/N42TI+OkDJruMcA==,type:str]
    #ENC[AES256_GCM,data:Y0HHGMZnaOgMi4oU,iv:3q7eTohQYP3rWHvA6G5N7RS59MCVhXcG1zIR1flRMpk=,tag:uz8JeKpjsZ7snIsyddzX5A==,type:comment]
    ZITADEL_DEFAULTINSTANCE_SMTPCONFIGURATION_SMTP_HOST: ENC[AES256_GCM,data:A8dDDb+swpNaXGxakhXqI3UV15I=,iv:oH7BUJ+ZByIsN+SK5LfmksWsdODUaPet93Dq/tuH4nc=,tag:B9sM88ZXUYGs//HcUF9J7g==,type:str]
    ZITADEL_DEFAULTINSTANCE_SMTPCONFIGURATION_SMTP_USER: ENC[AES256_GCM,data:SdImIVUJ,iv:8XsXI1SmGM0XOS1RKyVVNOmVFZNa8c8DluUOAzrF3BY=,tag:bC/aWJUK7gyHZE1qZ2Ajbw==,type:str]
    ZITADEL_DEFAULTINSTANCE_SMTPCONFIGURATION_SMTP_PASSWORD: ENC[AES256_GCM,data:zGjAOCepm0YsILVmee0D7NvRAs9XE1zgLwGPNHy5NhV4rb3y,iv:mLa6NatZRzWrmLlIOri/gZS2DJzTKzo6BozLjKz7jhk=,tag:3NNLkHa+cVoSU2xw8W6cdw==,type:str]
    ZITADEL_DEFAULTINSTANCE_SMTPCONFIGURATION_TLS: ENC[AES256_GCM,data:/bMRUg==,iv:w+9+1QXxs0zeGxkCLgPNLgqsf8/+fzgTn7Fpt5JjD4M=,tag:sqdIXA+ofc+TBExDjrGwAw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wy58yxmfdehpfyzwkw3kvqfkv0ze65lyf6yuhe5xt5n6md0vhyssnqkf2t
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTaEJ2Q1Q1NjFBVjg3SGs2
            OUZ1TmMzdHBGdW12QkpsSU5oa3pBeXN5Q0hrCmNjSXJSMTZ3dWp5S2Q2enNzQ2tY
            dXVQaW1paDg1QWdUeTVKR2Fjd0NjNk0KLS0tIDY5ekFIdVQrUHV5ZmNSalVzSkdS
            Z01KOTR2T0U1ZlZ1dnhRV0M0R2VXZFEKzc8ejNtvBFAkuBPHxoW1tdkJVgdUjIU+
            BVElccIjQhjetruD9Vr8572EtZxqrF4cypogNERYDDAAUe9z+z8MAA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-29T19:53:52Z"
    mac: ENC[AES256_GCM,data:ZmlphWXhIVh/0eySP8gNZWGzNRRyiqA/IszmO4WHJsSUZDAm7wzDm754tauEmSxwCFxHVCSEiU6VQXx62k83g3Bext8DZJfeNDehYmWRDxE5Kn1asJgxK5HAjoIwZ66ZHK2Vs6RS9bEvB0p10iRjzXAbKr5HeHlICg9P6TNiNig=,iv:vf7AG6XxxMvgQXs8nMaW50EtJ39ZaNok7FC+sYEtCkE=,tag:E7d0kd5ZXvlE2NmE9kMwLQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
