apiVersion: v1
kind: Secret
metadata:
    name: zitadel-secrets
    namespace: nethub
    labels:
        app.kubernetes.io/name: zitadel
        app.kubernetes.io/part-of: nethub
type: Opaque
stringData:
    masterkey: ENC[AES256_GCM,data:A0HBwU4e7LvLgKItrlX+Ij8jHd83GJySh40OSdy9oPk=,iv:tBvXC7/kgV+IrdeC1OVMASOvr1shqCJoJNHicmM+qV0=,tag:AOLs73w3P6rOZL2Zu7Vqbg==,type:str]
    ZITADEL_MASTERKEY: ENC[AES256_GCM,data:TTxEeWq0sRrcBdl9ksi372OdHVTaz9a0vCO9hklnu9c=,iv:rFtoGX8aKxSnqVea3pKDS4gIX2KT/6UT9wst1pxEroM=,tag:405v8hRqgDnRxxATyfUtQA==,type:str]
    #ENC[AES256_GCM,data:W6uVfNoAm2C7PpMak4JolvcU6z89wzwAZNzROYiiszU8jbmAhjIiDurE9mcJvED4I/zUsUQbz9R1Jw==,iv:iA+b7NjJDVZrmZSvkNeYVDj0yhUQGfqqNixEdo6K608=,tag:bMMQTRsEcV6W8SAMag+p7Q==,type:comment]
    ZITADEL_FIRSTINSTANCE_ORG_HUMAN_USERNAME: ENC[AES256_GCM,data:VvhVRGQ=,iv:gYiVYHyGdOHLVwbo89C7I+CXrohFYjBvSiZdjIqTQkY=,tag:cyUwwZj95Gdylr23DpC0Pw==,type:str]
    ZITADEL_FIRSTINSTANCE_ORG_HUMAN_PASSWORD: ENC[AES256_GCM,data:PNk1gTw65BKtz5CZD0NY/Njf2kVEjnSj,iv:fiKEN21gm2KcQlj/PNBef5uR7diUs77AgbPbjwWfObg=,tag:MblKnt+ii7/ktaRx1VGf2g==,type:str]
    ZITADEL_FIRSTINSTANCE_ORG_HUMAN_EMAIL: ENC[AES256_GCM,data:hzQmZqLOBYWfAAYZlp3cEtAa,iv:lKDffnuKD+c36HNHC4DphjAZr5KKJyz14w5Rxg540pI=,tag:GGi27duDUZvvgn9IhAwUUA==,type:str]
    #ENC[AES256_GCM,data:IHO9DmF3NzcW1YlkltqOxVdaWJGbZTMhqwsdW6ji39U7TYfJOWvYRxycKPM4qPDLBck=,iv:jN/5eu2CqE4h+MPiQC94bH/pF3Naz+QfHqhhLF+zLeE=,tag:zwZuiBnYkhKldbJHjRJzmw==,type:comment]
    ZITADEL_DATABASE_POSTGRES_HOST: ENC[AES256_GCM,data:zL8iE5kUrB8WhLJn0CNCD2fXMSG70JZYR4NhbeQ6IyM40mm0em/OS08Vs3Z9SYY=,iv:+8HR0IIO0NKf9a8ORbqWxufy9vUVssfZWBHD1Vy3UN8=,tag:RFe2LTB7Nz4sRFZ2WzLk1w==,type:str]
    ZITADEL_DATABASE_POSTGRES_PORT: ENC[AES256_GCM,data:1rAYIQ==,iv:8fVdOUrKZmS2+Q7MkJBdT3SKEJ4OtL6gvYOmC2AFCdQ=,tag:/+ANADk/UNhdibdOitx9uw==,type:str]
    ZITADEL_DATABASE_POSTGRES_DATABASE: ENC[AES256_GCM,data:4snS701+tA==,iv:ERLi4Z9gLWzq+wRi3sBUuUG3sEfMScEe1F3+g4phA3o=,tag:9je/nVFBGzSK+TUvVH3Rmw==,type:str]
    ZITADEL_DATABASE_POSTGRES_USER_USERNAME: ENC[AES256_GCM,data:X8zNhyy5YBejGTh3,iv:L25H87yLcE7etfQxwBRvoNoX3nu4YL300VDaaHHAGdw=,tag:hiUcFlEMmzIMywliULyXQg==,type:str]
    ZITADEL_DATABASE_POSTGRES_USER_PASSWORD: ENC[AES256_GCM,data:RvtyZYk/kTcpk2mPqVe7icKgjfXm0w==,iv:/WpKYzT05wxB8cp5ssHSEjnjmXnmmwW0tVNq7BaKw70=,tag:Zgt5pCemvrkSts2diWrYwA==,type:str]
    ZITADEL_DATABASE_POSTGRES_USER_SSL_MODE: ENC[AES256_GCM,data:eIQkUOhNBg==,iv:qsVeKWqnv11CyHx4cWOlqPpS5lGJid6be1laGB4t4Qw=,tag:5Le7CWUJy0FDsdoSe68BIQ==,type:str]
    ZITADEL_DATABASE_POSTGRES_ADMIN_USERNAME: ENC[AES256_GCM,data:xPplWKy/U+rfUdpK,iv:mtIBXVG+h+2gUwVLDAGWaC3sJPYXAlGKSkjZXaqX/8M=,tag:hnQSHSgS+P2qaaEUBD5F2g==,type:str]
    ZITADEL_DATABASE_POSTGRES_ADMIN_PASSWORD: ENC[AES256_GCM,data:2+L0KpGFv+eQHfze9TefIZ/OQkiJwg==,iv:nKswis9b/cDSRA6mKYOcaDpFWqdzF71qG6plO6BokWc=,tag:3X8xQHaNl5OOR1vhYvYVuQ==,type:str]
    ZITADEL_DATABASE_POSTGRES_ADMIN_SSL_MODE: ENC[AES256_GCM,data:IDQ12yR2Hg==,iv:/hqGc6OpXPrITGCoRbtLpl8bcNtESukZPXfsoZ1ht4k=,tag:q+C8p4gWIqKI7EFeG5Uehw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wy58yxmfdehpfyzwkw3kvqfkv0ze65lyf6yuhe5xt5n6md0vhyssnqkf2t
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrckRSeXVsdW4rblBuMER0
            c0NJemJmYzA2NmtIVkhJYTcyQ2NEc3l0ZHhZClcwNkpzYlFIV1hVaTBWcHA3YXl3
            eHg1Tm9oZ3Y3bkxIZEdDTjF1NzVheW8KLS0tIFp1Q1lCSC9iYW9yZCsvbEpTK2U4
            YzFBQzQ0dHRIQWwwNWQ2aE5JYkZkN28Kr8zPBdhk/QKYU1c3058uuUu5IJS3Slnx
            0alR+vSRgCipNAGM1j3hxAeX3vyCEfBaTURa3KO17bObvYDFgRSlow==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-29T15:04:06Z"
    mac: ENC[AES256_GCM,data:/Xw3wTU1WD8faLwXeY2oPprAGqvY4WkET1pIITR3fA6UWIJOCVMoGA3beFzpG2p3DsleNtMEI43thbJqv9umxrM18qCxh10U6OLmf/wvZ6wfReKUVYFtl3Hr+PnOxYIYMSdfv3FAAjk+uOutiWy0q424NP2KNjRKy4azf1EzjyQ=,iv:ezcU3EaPipfoFFVYM60k6v76sewVXilAm/48ERtl4+4=,tag:trvzkIfbjZ5iy/oil0jNeg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
